services:
  web:
    image: ghcr.io/smart-village-solutions/guben-cockpit-web:${RELEASE_TAG:-v0.8.7}
    build: null

  web-live:
    image: ghcr.io/smart-village-solutions/guben-cockpit-web:${RELEASE_TAG:-v0.8.7}
    build: null

  content-gateway:
    image: ghcr.io/smart-village-solutions/guben-cockpit-content-gateway:${RELEASE_TAG:-v0.8.7}
    build: null
