sonar.projectKey=smart-village-solutions_guben-cockpit-old
sonar.projectName=guben-cockpit-old
sonar.sourceEncoding=UTF-8

sonar.sources=content-gateway/src,frontend/src,shared/public-content
sonar.tests=content-gateway/test,frontend/src,shared/public-content

sonar.test.inclusions=content-gateway/test/**/*.test.ts,frontend/src/**/*.test.ts,frontend/src/**/*.test.tsx,shared/public-content/**/*.test.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,frontend/src/assets/**,frontend/src/routeTree.gen.ts,frontend/src/vite-env.d.ts,frontend/src/utilities/i18n/@types/**,**/*.d.ts

sonar.javascript.lcov.reportPaths=content-gateway/coverage/lcov.info,frontend/coverage/lcov.info,shared/coverage/lcov.info
