services:
  guben-db-prod:
    container_name: guben-db-prod
    restart: unless-stopped
    image: postgres:17
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - guben-data-prod:/var/lib/postgresql/data/
    networks:
      - guben_prod

networks:
  guben_prod:
    driver: bridge

volumes:
  guben-data-prod:
    external: true
    name: cockpit_guben-data-prod
