/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MapImport } from './routes/map'
import { Route as EventsImport } from './routes/events'
import { Route as BuilderPreviewImport } from './routes/builder-preview'
import { Route as IndexImport } from './routes/index'
import { Route as EventsIndexImport } from './routes/events/index'
import { Route as BookingIndexImport } from './routes/booking/index'
import { Route as ProjectsProjectIdImport } from './routes/projects/$projectId'
import { Route as EventsEventIdImport } from './routes/events/$eventId'
import { Route as BookingTitleImport } from './routes/booking/$title'
import { Route as BookingRoomTitleImport } from './routes/booking/room/$title'

// Create Virtual Routes

const ProjectsLazyImport = createFileRoute('/projects')()
const ProjectsIndexLazyImport = createFileRoute('/projects/')()
const ProjectsSchoolsLazyImport = createFileRoute('/projects/schools')()
const ProjectsMarketplaceLazyImport = createFileRoute('/projects/marketplace')()

// Create/Update Routes

const ProjectsLazyRoute = ProjectsLazyImport.update({
  path: '/projects',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/projects.lazy').then((d) => d.Route))

const MapRoute = MapImport.update({
  path: '/map',
  getParentRoute: () => rootRoute,
} as any)

const EventsRoute = EventsImport.update({
  path: '/events',
  getParentRoute: () => rootRoute,
} as any)

const BuilderPreviewRoute = BuilderPreviewImport.update({
  path: '/builder-preview',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsIndexLazyRoute = ProjectsIndexLazyImport.update({
  path: '/',
  getParentRoute: () => ProjectsLazyRoute,
} as any).lazy(() =>
  import('./routes/projects/index.lazy').then((d) => d.Route),
)

const EventsIndexRoute = EventsIndexImport.update({
  path: '/',
  getParentRoute: () => EventsRoute,
} as any)

const BookingIndexRoute = BookingIndexImport.update({
  path: '/booking/',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsSchoolsLazyRoute = ProjectsSchoolsLazyImport.update({
  path: '/schools',
  getParentRoute: () => ProjectsLazyRoute,
} as any).lazy(() =>
  import('./routes/projects/schools.lazy').then((d) => d.Route),
)

const ProjectsMarketplaceLazyRoute = ProjectsMarketplaceLazyImport.update({
  path: '/marketplace',
  getParentRoute: () => ProjectsLazyRoute,
} as any).lazy(() =>
  import('./routes/projects/marketplace.lazy').then((d) => d.Route),
)

const ProjectsProjectIdRoute = ProjectsProjectIdImport.update({
  path: '/$projectId',
  getParentRoute: () => ProjectsLazyRoute,
} as any)

const EventsEventIdRoute = EventsEventIdImport.update({
  path: '/$eventId',
  getParentRoute: () => EventsRoute,
} as any)

const BookingTitleRoute = BookingTitleImport.update({
  path: '/booking/$title',
  getParentRoute: () => rootRoute,
} as any)

const BookingRoomTitleRoute = BookingRoomTitleImport.update({
  path: '/booking/room/$title',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/builder-preview': {
      id: '/builder-preview'
      path: '/builder-preview'
      fullPath: '/builder-preview'
      preLoaderRoute: typeof BuilderPreviewImport
      parentRoute: typeof rootRoute
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsImport
      parentRoute: typeof rootRoute
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapImport
      parentRoute: typeof rootRoute
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsLazyImport
      parentRoute: typeof rootRoute
    }
    '/booking/$title': {
      id: '/booking/$title'
      path: '/booking/$title'
      fullPath: '/booking/$title'
      preLoaderRoute: typeof BookingTitleImport
      parentRoute: typeof rootRoute
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdImport
      parentRoute: typeof EventsImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdImport
      parentRoute: typeof ProjectsLazyImport
    }
    '/projects/marketplace': {
      id: '/projects/marketplace'
      path: '/marketplace'
      fullPath: '/projects/marketplace'
      preLoaderRoute: typeof ProjectsMarketplaceLazyImport
      parentRoute: typeof ProjectsLazyImport
    }
    '/projects/schools': {
      id: '/projects/schools'
      path: '/schools'
      fullPath: '/projects/schools'
      preLoaderRoute: typeof ProjectsSchoolsLazyImport
      parentRoute: typeof ProjectsLazyImport
    }
    '/booking/': {
      id: '/booking/'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingIndexImport
      parentRoute: typeof rootRoute
    }
    '/events/': {
      id: '/events/'
      path: '/'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexImport
      parentRoute: typeof EventsImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexLazyImport
      parentRoute: typeof ProjectsLazyImport
    }
    '/booking/room/$title': {
      id: '/booking/room/$title'
      path: '/booking/room/$title'
      fullPath: '/booking/room/$title'
      preLoaderRoute: typeof BookingRoomTitleImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface EventsRouteChildren {
  EventsEventIdRoute: typeof EventsEventIdRoute
  EventsIndexRoute: typeof EventsIndexRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsEventIdRoute: EventsEventIdRoute,
  EventsIndexRoute: EventsIndexRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

interface ProjectsLazyRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  ProjectsMarketplaceLazyRoute: typeof ProjectsMarketplaceLazyRoute
  ProjectsSchoolsLazyRoute: typeof ProjectsSchoolsLazyRoute
  ProjectsIndexLazyRoute: typeof ProjectsIndexLazyRoute
}

const ProjectsLazyRouteChildren: ProjectsLazyRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  ProjectsMarketplaceLazyRoute: ProjectsMarketplaceLazyRoute,
  ProjectsSchoolsLazyRoute: ProjectsSchoolsLazyRoute,
  ProjectsIndexLazyRoute: ProjectsIndexLazyRoute,
}

const ProjectsLazyRouteWithChildren = ProjectsLazyRoute._addFileChildren(
  ProjectsLazyRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/builder-preview': typeof BuilderPreviewRoute
  '/events': typeof EventsRouteWithChildren
  '/map': typeof MapRoute
  '/projects': typeof ProjectsLazyRouteWithChildren
  '/booking/$title': typeof BookingTitleRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/marketplace': typeof ProjectsMarketplaceLazyRoute
  '/projects/schools': typeof ProjectsSchoolsLazyRoute
  '/booking': typeof BookingIndexRoute
  '/events/': typeof EventsIndexRoute
  '/projects/': typeof ProjectsIndexLazyRoute
  '/booking/room/$title': typeof BookingRoomTitleRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/builder-preview': typeof BuilderPreviewRoute
  '/map': typeof MapRoute
  '/booking/$title': typeof BookingTitleRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/marketplace': typeof ProjectsMarketplaceLazyRoute
  '/projects/schools': typeof ProjectsSchoolsLazyRoute
  '/booking': typeof BookingIndexRoute
  '/events': typeof EventsIndexRoute
  '/projects': typeof ProjectsIndexLazyRoute
  '/booking/room/$title': typeof BookingRoomTitleRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/builder-preview': typeof BuilderPreviewRoute
  '/events': typeof EventsRouteWithChildren
  '/map': typeof MapRoute
  '/projects': typeof ProjectsLazyRouteWithChildren
  '/booking/$title': typeof BookingTitleRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/marketplace': typeof ProjectsMarketplaceLazyRoute
  '/projects/schools': typeof ProjectsSchoolsLazyRoute
  '/booking/': typeof BookingIndexRoute
  '/events/': typeof EventsIndexRoute
  '/projects/': typeof ProjectsIndexLazyRoute
  '/booking/room/$title': typeof BookingRoomTitleRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/builder-preview'
    | '/events'
    | '/map'
    | '/projects'
    | '/booking/$title'
    | '/events/$eventId'
    | '/projects/$projectId'
    | '/projects/marketplace'
    | '/projects/schools'
    | '/booking'
    | '/events/'
    | '/projects/'
    | '/booking/room/$title'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/builder-preview'
    | '/map'
    | '/booking/$title'
    | '/events/$eventId'
    | '/projects/$projectId'
    | '/projects/marketplace'
    | '/projects/schools'
    | '/booking'
    | '/events'
    | '/projects'
    | '/booking/room/$title'
  id:
    | '__root__'
    | '/'
    | '/builder-preview'
    | '/events'
    | '/map'
    | '/projects'
    | '/booking/$title'
    | '/events/$eventId'
    | '/projects/$projectId'
    | '/projects/marketplace'
    | '/projects/schools'
    | '/booking/'
    | '/events/'
    | '/projects/'
    | '/booking/room/$title'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuilderPreviewRoute: typeof BuilderPreviewRoute
  EventsRoute: typeof EventsRouteWithChildren
  MapRoute: typeof MapRoute
  ProjectsLazyRoute: typeof ProjectsLazyRouteWithChildren
  BookingTitleRoute: typeof BookingTitleRoute
  BookingIndexRoute: typeof BookingIndexRoute
  BookingRoomTitleRoute: typeof BookingRoomTitleRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuilderPreviewRoute: BuilderPreviewRoute,
  EventsRoute: EventsRouteWithChildren,
  MapRoute: MapRoute,
  ProjectsLazyRoute: ProjectsLazyRouteWithChildren,
  BookingTitleRoute: BookingTitleRoute,
  BookingIndexRoute: BookingIndexRoute,
  BookingRoomTitleRoute: BookingRoomTitleRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/builder-preview",
        "/events",
        "/map",
        "/projects",
        "/booking/$title",
        "/booking/",
        "/booking/room/$title"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/builder-preview": {
      "filePath": "builder-preview.tsx"
    },
    "/events": {
      "filePath": "events.tsx",
      "children": [
        "/events/$eventId",
        "/events/"
      ]
    },
    "/map": {
      "filePath": "map.tsx"
    },
    "/projects": {
      "filePath": "projects.lazy.tsx",
      "children": [
        "/projects/$projectId",
        "/projects/marketplace",
        "/projects/schools",
        "/projects/"
      ]
    },
    "/booking/$title": {
      "filePath": "booking/$title.tsx"
    },
    "/events/$eventId": {
      "filePath": "events/$eventId.tsx",
      "parent": "/events"
    },
    "/projects/$projectId": {
      "filePath": "projects/$projectId.tsx",
      "parent": "/projects"
    },
    "/projects/marketplace": {
      "filePath": "projects/marketplace.lazy.tsx",
      "parent": "/projects"
    },
    "/projects/schools": {
      "filePath": "projects/schools.lazy.tsx",
      "parent": "/projects"
    },
    "/booking/": {
      "filePath": "booking/index.tsx"
    },
    "/events/": {
      "filePath": "events/index.tsx",
      "parent": "/events"
    },
    "/projects/": {
      "filePath": "projects/index.lazy.tsx",
      "parent": "/projects"
    },
    "/booking/room/$title": {
      "filePath": "booking/room/$title.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
