/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MapImport } from './routes/map'
import { Route as EventsImport } from './routes/events'
import { Route as IndexImport } from './routes/index'
import { Route as EventsIndexImport } from './routes/events/index'
import { Route as BookingIndexImport } from './routes/booking/index'
import { Route as EventsEventIdImport } from './routes/events/$eventId'
import { Route as BookingTitleImport } from './routes/booking/$title'
import { Route as BookingRoomTitleImport } from './routes/booking/room/$title'

// Create Virtual Routes

const ProjectsLazyImport = createFileRoute('/projects')()

// Create/Update Routes

const ProjectsLazyRoute = ProjectsLazyImport.update({
  path: '/projects',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/projects.lazy').then((d) => d.Route))

const MapRoute = MapImport.update({
  path: '/map',
  getParentRoute: () => rootRoute,
} as any)

const EventsRoute = EventsImport.update({
  path: '/events',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const EventsIndexRoute = EventsIndexImport.update({
  path: '/',
  getParentRoute: () => EventsRoute,
} as any)

const BookingIndexRoute = BookingIndexImport.update({
  path: '/booking/',
  getParentRoute: () => rootRoute,
} as any)

const EventsEventIdRoute = EventsEventIdImport.update({
  path: '/$eventId',
  getParentRoute: () => EventsRoute,
} as any)

const BookingTitleRoute = BookingTitleImport.update({
  path: '/booking/$title',
  getParentRoute: () => rootRoute,
} as any)

const BookingRoomTitleRoute = BookingRoomTitleImport.update({
  path: '/booking/room/$title',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsImport
      parentRoute: typeof rootRoute
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapImport
      parentRoute: typeof rootRoute
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsLazyImport
      parentRoute: typeof rootRoute
    }
    '/booking/$title': {
      id: '/booking/$title'
      path: '/booking/$title'
      fullPath: '/booking/$title'
      preLoaderRoute: typeof BookingTitleImport
      parentRoute: typeof rootRoute
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdImport
      parentRoute: typeof EventsImport
    }
    '/booking/': {
      id: '/booking/'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingIndexImport
      parentRoute: typeof rootRoute
    }
    '/events/': {
      id: '/events/'
      path: '/'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexImport
      parentRoute: typeof EventsImport
    }
    '/booking/room/$title': {
      id: '/booking/room/$title'
      path: '/booking/room/$title'
      fullPath: '/booking/room/$title'
      preLoaderRoute: typeof BookingRoomTitleImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface EventsRouteChildren {
  EventsEventIdRoute: typeof EventsEventIdRoute
  EventsIndexRoute: typeof EventsIndexRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsEventIdRoute: EventsEventIdRoute,
  EventsIndexRoute: EventsIndexRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events': typeof EventsRouteWithChildren
  '/map': typeof MapRoute
  '/projects': typeof ProjectsLazyRoute
  '/booking/$title': typeof BookingTitleRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/booking': typeof BookingIndexRoute
  '/events/': typeof EventsIndexRoute
  '/booking/room/$title': typeof BookingRoomTitleRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/map': typeof MapRoute
  '/projects': typeof ProjectsLazyRoute
  '/booking/$title': typeof BookingTitleRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/booking': typeof BookingIndexRoute
  '/events': typeof EventsIndexRoute
  '/booking/room/$title': typeof BookingRoomTitleRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/events': typeof EventsRouteWithChildren
  '/map': typeof MapRoute
  '/projects': typeof ProjectsLazyRoute
  '/booking/$title': typeof BookingTitleRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/booking/': typeof BookingIndexRoute
  '/events/': typeof EventsIndexRoute
  '/booking/room/$title': typeof BookingRoomTitleRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/events'
    | '/map'
    | '/projects'
    | '/booking/$title'
    | '/events/$eventId'
    | '/booking'
    | '/events/'
    | '/booking/room/$title'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/map'
    | '/projects'
    | '/booking/$title'
    | '/events/$eventId'
    | '/booking'
    | '/events'
    | '/booking/room/$title'
  id:
    | '__root__'
    | '/'
    | '/events'
    | '/map'
    | '/projects'
    | '/booking/$title'
    | '/events/$eventId'
    | '/booking/'
    | '/events/'
    | '/booking/room/$title'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventsRoute: typeof EventsRouteWithChildren
  MapRoute: typeof MapRoute
  ProjectsLazyRoute: typeof ProjectsLazyRoute
  BookingTitleRoute: typeof BookingTitleRoute
  BookingIndexRoute: typeof BookingIndexRoute
  BookingRoomTitleRoute: typeof BookingRoomTitleRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventsRoute: EventsRouteWithChildren,
  MapRoute: MapRoute,
  ProjectsLazyRoute: ProjectsLazyRoute,
  BookingTitleRoute: BookingTitleRoute,
  BookingIndexRoute: BookingIndexRoute,
  BookingRoomTitleRoute: BookingRoomTitleRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/events",
        "/map",
        "/projects",
        "/booking/$title",
        "/booking/",
        "/booking/room/$title"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/events": {
      "filePath": "events.tsx",
      "children": [
        "/events/$eventId",
        "/events/"
      ]
    },
    "/map": {
      "filePath": "map.tsx"
    },
    "/projects": {
      "filePath": "projects.lazy.tsx"
    },
    "/booking/$title": {
      "filePath": "booking/$title.tsx"
    },
    "/events/$eventId": {
      "filePath": "events/$eventId.tsx",
      "parent": "/events"
    },
    "/booking/": {
      "filePath": "booking/index.tsx"
    },
    "/events/": {
      "filePath": "events/index.tsx",
      "parent": "/events"
    },
    "/booking/room/$title": {
      "filePath": "booking/room/$title.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
