name: Build and push Docker image on tag

on:
  push:
    tags:
      - 'v*.*.*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: agriculturedev/guben-cockpit

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    environment: main
    permissions:
      contents: read
      packages: write
    env:
      VITE_CONTENT_GATEWAY_URL: ${{ vars.VITE_CONTENT_GATEWAY_URL }}
      VITE_BOOKING_SDK: ${{ vars.VITE_BOOKING_SDK }}
      VITE_BOOKING_LOGIN: ${{ vars.VITE_BOOKING_LOGIN }}
      VITE_BOOKING_URL: ${{ vars.VITE_BOOKING_URL }}
      VITE_TRANSLATE_URL: ${{ vars.VITE_TRANSLATE_URL }}
      VITE_TRANSLATE_API_KEY: ${{ vars.VITE_TRANSLATE_API_KEY }}
      VITE_MATOMO_JS: ${{ vars.VITE_MATOMO_JS }}
      VITE_MASTERPORTAL_URL: ${{ vars.VITE_MASTERPORTAL_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta-web
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-web

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: ${{ steps.meta-web.outputs.tags }}
          labels: ${{ steps.meta-web.outputs.labels }}
          build-args: |
            VITE_CONTENT_GATEWAY_URL=${{ vars.VITE_CONTENT_GATEWAY_URL }}
            VITE_BOOKING_SDK=${{ vars.VITE_BOOKING_SDK }}
            VITE_BOOKING_LOGIN=${{ vars.VITE_BOOKING_LOGIN }}
            VITE_BOOKING_URL=${{ vars.VITE_BOOKING_URL }}
            VITE_TRANSLATE_URL=${{ vars.VITE_TRANSLATE_URL }}
            VITE_TRANSLATE_API_KEY=${{ vars.VITE_TRANSLATE_API_KEY }}
            VITE_MATOMO_JS=${{ vars.VITE_MATOMO_JS }}
            VITE_MASTERPORTAL_URL=${{ vars.VITE_MASTERPORTAL_URL }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta-gateway
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-content-gateway

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./content-gateway
          push: true
          tags: ${{ steps.meta-gateway.outputs.tags }}
          labels: ${{ steps.meta-gateway.outputs.labels }}
